export { default as Article } from './article/Article';
export { default as Brand } from './brand/Brand';
export { default as CTA } from './cta/CTA';
export { default as Feature } from './feature/Feature';
export { default as Navbar } from './navbar/Navbar';
export { default as Dashboard } from './dashboard/Dashboard';
export { default as CenterConetnt } from './centerContent/CenterContent';
export { default as LeftMenu } from './leftMenu/LeftMenu';
export { default as RightMenu } from './rightMenu/RightMenu';
